apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking-app
  namespace: ticket-booking
  labels:
    app: ticket-booking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-booking-app
  template:
    metadata:
      labels:
        app: ticket-booking-app
    spec:
      containers:
      - name: ticket-booking-app
        image: tvrcharan/ticket-booking-app:latest   # ✅ use your actual Docker Hub image
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
