apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
  namespace: ticket-booking
spec:
  type: NodePort
  selector:
    app: ticket-booking-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
